import { type NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import type { ItemProperty } from "../types/item";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const item = trpc.example.hello.useQuery();
  
  useEffect(() => {
    console.log("items", item);
  }, [item]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-4xl font-bold text-gray-700">
          Hello World
        </h1>
        <div className="flex flex-col">
          <span className="text-gray-700">{item?.data?.name}</span>
          <span className="text-gray-700">{item?.data?.maxSupply}</span>
          <ul>
          {
            item?.data?.properties.map((property: ItemProperty, index) => (
              <li key={`item-${index}`}>
                <span className="text-gray-700">{property.name}</span>
                <span className="text-gray-700">{property.value}</span>
              </li>
            ))
          }
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;